version: "3.8"

services:
  app:
    container_name: job-scheduler
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=dev
      - VERSION=1.0
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    tty: true
    #commands: node --inspect=0.0.0.0:9229 dist/main.js
    #commands: "npm start"

